name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build using Makefile
      run: make release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Binary to Release
      uses: actions/upload-release-asset@v1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dnsTools-linux
        asset_name: dnsTools-linux
        asset_content_type: application/octet-stream
